PACKAGE_SOURCE="filepath/to/ss/source/folder" #can set both package.nw or the entire source source folder

#No need to change unless you know what you are doing
APP_NAME="Succubus Stories (Linux)"
APP_COMMENT="Play this game on Linux native"
DESKTOP_FILENAME="SS.desktop"
ICON_PATH="/assets/favicon.png"
EXECUTABLE="nw"
FORCE=false

PACKAGE_LINK="package.nw"
NWJS_VERSION="0.94.0"
ARCH="linux-x64"
BUILD="normal"
